package com.christopheradams.ch2challenges.num005SalesPredition;

/**
 * Created by Christopher on 5/12/2016.
 * The east coast division of a company
 * generates 62 percent of total sales.
 * The program calculates how much money is generated by
 * the east coast if total generated is 4.6 million.
 */
public class Challenge5SalesPrediction
{
    public static void main(String[]args)
    {
        double sales = 4600000;
        double eastCoastSales = sales * .62;

        System.out.println("The total sales generate by the east coast" +
                            " division is " + eastCoastSales + ".\n");

    }
}
